language: java
jdk:
  - opendjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - freshsangmin@gmail.com