language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_deploy:
  - zip -r mycarrot4 *
  - mkdir -p deploy
  - mv mycarrot4.zip deploy/mycarrot4.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mycarrot4-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: mycarrot4-springboot-build
    key: mycarrot4.zip
    bundle_type: zip
    application: mycarrot4
    deployment_group: mycarrot4-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - freshsangmin@gmail.com